# X - WIDTH, F - FIX
# Z - HEIGHT
# T - THICKNESS
# TOL - TOLERANCE
# D - DIAMETER
# Y - DEEP
# O - OFFSET
# PO - POCKET
# R - RADIUS

TOL_F = 0.05

BACK_Y_F = 114 # 114
WALL_X = BACK_Y_F / 114 * 171
WALL_Z = BACK_Y_F
WALL_T = BACK_Y_F / 114 * 1
BACK_X_O = (WALL_X - WALL_T) / 2
LEFT_Y_O = (BACK_Y_F + WALL_T) / 2

LEG_X = BACK_Y_F / 114 * 18
LEG_T = LEG_X / 8

BOTTOM_T = BACK_Y_F / 114 * 2
BOTTOM_Z = BACK_Y_F / 114 * 8
BOTTOM_X = WALL_X + TOL_F * 2 + BOTTOM_T * 2
BOTTOM_Y = BACK_Y_F + (BOTTOM_T + WALL_T + TOL_F) * 2
BOTTOM_Z_O = WALL_Z / 2 + BOTTOM_T

EAR_X = LEG_X + TOL_F * 2 + BOTTOM_T * 2
EAR_X_O = BOTTOM_X / 2 - EAR_X - EAR_X / 2
EAR_Y = (LEG_T + TOL_F * 2 + BOTTOM_T) * 2 + BOTTOM_Y

WALL_HOLDER_O = WALL_T + TOL_F * 2
HOLDER_X = EAR_X - BOTTOM_T - WALL_HOLDER_O
HOLDER_X_O = BOTTOM_X / 2 - BOTTOM_T - WALL_HOLDER_O
HOLDER_Y_O = BOTTOM_Y / 2 - BOTTOM_T - WALL_HOLDER_O

LEG_Z = BACK_Y_F / 114 * 180
LEG_PART_Z = WALL_Z + BOTTOM_T * 3
LEG_FILLET = BACK_Y_F / 114 * 0.5

TOP_Z = BOTTOM_Z - BOTTOM_T

LAMP_D_F = 76
LAMP_D2_F = 85
LAMP_ARC_Y_F = 24
LAMP_DOOR_O	= BOTTOM_X / 2
LAMP_BOLT_O_F = 2.5
LAMP_BOLT_O2_F = 62
LAMP_BOLT_D_F = 2
LAMP_BOLT_D2_F = 5.5
LAMP_BOLT_Z_F = 1.5

TUBE_D = BACK_Y_F / 114 * 40
TUBE_T = BOTTOM_T / 2
TUBE_BACK_O	= BACK_Y_F / 114 * 40
TUBE_Z = BACK_Y_F / 114 * 150
TUBE_X_O = BOTTOM_X / 2 - TUBE_BACK_O
TUBE_Z_O = BOTTOM_Z_O - BOTTOM_T - TUBE_T
TUBE_INTERNAL_D = TUBE_D - TUBE_T * 2
TUBE_EXTERNAL_D = TUBE_INTERNAL_D + TUBE_D / 5

DOOR_Y_O = BACK_Y_F / 114 * 15
DOOR_Z_O = BACK_Y_F / 114 * 15
DOOR_O = BACK_Y_F / 114 * 0.5
DOOR_Z = WALL_Z / 114 * 70

FRONT_HOLES_F = 9
FRONT_T = BOTTOM_T / 2
FRONT_HOLE_D = BACK_Y_F / 114 * 8
FRONT_HOLE_Z_O = BACK_Y_F / 114 * 12

HINGE_Y = BACK_Y_F / 114 * 10
HINGE_D = HINGE_Y / 10 * 3.2
HINGE_Z = HINGE_Y / 10 * 4
LOCK_X = HINGE_D
LOCK_Z = BACK_Y_F / 114 * 10
LOCK_T = LOCK_X
LOCK_T1 = LOCK_T / 3 * 2
LOCK_T2 = LOCK_T - LOCK_T1

AXLE_D = HINGE_Y / 10 * 2.6

DOOR_LATCH_R1 = AXLE_D / 2 + 1 + TOL_F * 2
DOOR_LATCH_R2 = AXLE_D / 2 + TOL_F * 2

FRONT_DOOR_X = BACK_Y_F-DOOR_Y_O*2
FRONT_DOOR_Z = DOOR_Z+DOOR_O*2
FRONT_DOOR_CENTER_Z_O = WALL_Z/2-DOOR_Z_O-FRONT_DOOR_Z/2

HINGE_CENTER_Y_O = HINGE_Y/4+DOOR_O/2

LATCH_Y = LOCK_Z / 10 * 20
LATCH_AXLE_O = LATCH_Y / 4
LATCH_R1 = AXLE_D / 2 + 1

